<?php
require '../app/utils.php';
/*
  Problem 2 https://projecteuler.net/problem=2
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.
 */
$n = 0;
$sum = 0;
for ($i = 0; $n <= 4000000; $i++) {
    $n = round(pow((sqrt(5) + 1) / 2, $i) / sqrt(5));
    $sum += $n % 2 == 0 ? $n : 0;
}
echo $sum;

require '../app/running_time.php';
